runtime: python
api_version: 1
vm: true
entrypoint:

runtime_config:
  operating_system: "ubuntu22"
  python_version: "2.7"
  env: flex

handlers:
  - url: /.*
    script: app.app

libraries:
  - name: flask
    version: 0.12